server:
  port: 80

spring:
  application:
    name: cloud-order-service
# fixme 废弃
#  zipkin:
#    base-url: http://192.168.32.120:30008
#    sleuth:
#      sampler:
        # 采样率值介于0-1之间，1则表示全部采集
#        probability: 1
management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      #endpoint: http://localhost:9411/api/v2/spans
      endpoint: http://192.168.32.120:30008/api/v2/spans
      connect-timeout: 1s
      read-timeout: 10s
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  pattern:
    level: "%5p [${spring.application.name:test},%X{traceId:-},%X{spanId:-}]"

### eureka相关配置
eureka:
  client:
    # 表示将自己注册进EurekaServer, 默认为true
    register-with-eureka: true
    # 是否从EurekaServer 抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负责均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: order80
    prefer-ip-address: true
    # Eureka客户端向服务端发送心跳的实际间隔，单位为秒（默认为30秒）
    lease-renewal-interval-in-seconds: 1
    # Eureka服务端收到最后一次心跳后等待时间上线，单位为秒（默认为90秒） 超时将剔除服务
    lease-expiration-duration-in-seconds: 2
