server:
  port: 9002
spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        # 访问nginx代理端口
        server-addr: 192.168.94.133:1111
      # 配置nacos地址
#        server-addr: localhost:8848
management:
  endpoints:
    web:
      exposure:
        include: "*"
