server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          # 开启从注册中心动态创建路由的功能，利用服务名称进行路由
          enabled: true
      routes:
        - id: payment_routh # payment_route     # 路由的ID，没有固定规则但要求唯一，建议配合服务名
          #          uri: http://localhost:8001            # 匹配后提供服务的路由地址
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/get/**              # 断言；路径相匹配的进行路由

        - id: payment_routh2 # payment_route    # 路由的ID，没有固定规则但要求唯一，建议配合服务名
          #          uri: http://localhost:8001            # 匹配后提供服务的路由地址
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/lb/**               # 断言；路径相匹配的进行路由
#            - Before=2024-01-20T17:17:47.571-07:00[Asia/Shanghai]
#            - After=2024-01-18T15:41:00.000-00:00[Asia/Shanghai]
#            - Between=2024-01-18T15:31:56.571-07:00[Asia/Shanghai], 2024-01-28T15:46:47.571-07:00[Asia/Shanghai]
#            - Cookie=username,apelx
#            - Header=X-Request-Id,\d+ #请求头要包含X-Request-Id属性，并且值为整数的正则表达式
#            - Host=**.apelx.com
#            - Method=GET
#            - Query=green, 1
          filters:
            - AddRequestHeader=X-Request-red,blue # 过滤工厂会在匹配的请求头加上一对请求头，名称为 X-Request-Id 值为 blue

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    # 表示将自己注册进EurekaServer, 默认为true
    register-with-eureka: true
    # 是否从EurekaServer 抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负责均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka