server:
  port: 7777
spring:
  application:
    name: distributed-id-generator
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
management:
  endpoints:
    web:
      exposure:
        include: '*'
