server:
  port: 7777
spring:
  application:
    name: distributed-id-generator
  cloud:
    nacos:
      discovery:
        #server-addr: localhost:8848
        server-addr: 192.168.32.120:30006
management:
  endpoints:
    web:
      exposure:
        include: '*'
