server:
  port: 8401
spring:
  application:
    name: cloud-alibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        # nacos服务注册中心地址
        #server-addr: localhost:8848
        server-addr: 192.168.32.120:30006
#        group: spring-cloud-sgg
#        namespace: 3dbb835a-9df7-48c5-83c1-746b2b16a3e5
    sentinel:
      transport:
        # 配置 sentinel dashboard地址
        #dashboard: localhost:8080
        dashboard: 192.168.32.120:30004
        # 默认8719端口，假如被占用了会自动从8719端口+1进行扫描，直到找到未被占用的 端口
        port: 30005
      web-context-unify: false # 关闭context整合
      datasource:
        ds1:
          nacos:
            server-addr: 192.168.32.120:30006
            dataId: cloud-alibaba-sentinel-service
#            groupId: spring-cloud-sgg
#            namespace: 3dbb835a-9df7-48c5-83c1-746b2b16a3e5
            data-type: json
            rule-type: flow

management:
  endpoints:
    web:
      exposure:
        include: '*'

feign:
  sentinel:
    enabled: true
