server:
  port: 84

spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        #server-addr: localhost:8848
        server-addr: 192.168.32.120:30006
#        namespace: 3dbb835a-9df7-48c5-83c1-746b2b16a3e5
#        group: spring-cloud-sgg
    sentinel:
      transport:
        # 配置sentinel dashboard地址
        #dashboard: localhost:8080
        dashboard: 192.168.32.120:30004
        # 默认8719端口，假如被占用会自动从8719开始依次+1扫描，直至找到未被占用的端口
        port: 30005
    openfeign:
      client:
        config:
          default:
            connectTimeout: 3000
            readTimeout: 3000
            loggerLevel: full


# 自定义配置 - 消费者将要去访问的微服务名称（注册成功进nacos的微服务提供者）
service-url:
  nacos-user-service: http://nacos-payment-provider

# 激活sentinel对feign的支持
feign:
  sentinel:
    enabled: true
