server:
  port: 9002
spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        # 访问nginx代理端口
#        server-addr: 192.168.94.133:1111
      # 配置nacos地址
        server-addr: 192.168.32.120:30006
#        group: spring-cloud-sgg
#        namespace: 3dbb835a-9df7-48c5-83c1-746b2b16a3e5

management:
  endpoints:
    web:
      exposure:
        include: "*"
