server:
  port: 83
spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        group: spring-cloud-sgg
        namespace: 3dbb835a-9df7-48c5-83c1-746b2b16a3e5


# 消费者将要去访问的微服务名称（注册成功进nocos的微服务提供者）
service-url:
  nacos-user-service: http://nacos-payment-provider
