server:
  port: 80

spring:
  application:
    name: cloud-feign-hystrix-order
  cloud:
    openfeign:
      client:
        config:
          default:
            connect-timeout: 3000
            read-timeout: 3000
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
logging:
  level:
    cn.apelx.springcloud.service.OrderHystrixMain80: debug
# feign中开启hystrix
feign:
  hystrix:
    enabled: true